apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: "."
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-demo
    targetRevision: 0.40.5
    helm:
      valuesObject:
        default:
          podAnnotations:
            git.repository: "https://github.com/jas-atwal/otel-argocd"
            git.branch: "main"
            argocd.argoproj.io/app-name: "otel-demo-prod"

        components:
          flagd:
            enabled: true
            service:
              type: LoadBalancer
          frontend-proxy:
            enabled: true
            service:
              type: LoadBalancer
          cart:
            resources:
              limits:
                memory: 160Mi
          llm:
            enabled: false

        grafana:
          enabled: true
        jaeger:
          enabled: true
        opentelemetry-collector:
          enabled: true
        opensearch:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
