components:
  checkout:
    envOverrides:
      - name: SHIPPING_SERVICE_ADDR
        value: "http://shippingservices:8080"
  flagd:
    enabled: true
  frontend-proxy:
    enabled: true
    service:
      type: LoadBalancer
  cart:
    resources:
      limits:
        memory: 160Mi
  llm:
    enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
jaeger:
  enabled: false
opentelemetry-collector:
  enabled: true
opensearch:
  enabled: false
